package view;

import dao.DaoAtualizar;
import dao.DaoRotinas;
import dao.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author guilherme.krug
 */
public class Desatualizacao extends javax.swing.JFrame {

    /**
     * Creates new form Totalizacao
     */
    public Desatualizacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        btnAttMes = new javax.swing.JButton();
        data = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        anterior = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAttAno = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        atual = new javax.swing.JTextField();
        credoudeb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAttMes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAttMes.setText("VOLTAR MÊS");
        btnAttMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttMesActionPerformed(evt);
            }
        });

        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Data desejada");

        anterior.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Valor anterior");

        btnAttAno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAttAno.setText("VOLTAR ANO");
        btnAttAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttAnoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("FECHAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Valor atual");

        atual.setEnabled(false);

        credoudeb.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Débito ou Credito");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAttMes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAttAno))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(atual, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anterior, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(credoudeb, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(data, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)))
                .addGap(118, 118, 118))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(307, 307, 307))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anterior)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(atual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(credoudeb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(159, 159, 159)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAttMes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAttAno, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAttMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttMesActionPerformed
        String mesAno = data.getText().trim(); // MM/yyyy

        if (mesAno.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o mês/ano no formato MM/yyyy!");
            return;
        }

// Cria a conexão
        DataSource dataSource = new DataSource();
        DaoRotinas dao = new DaoRotinas(dataSource);

        try {
            // 1) Executa a virada de mês
            dao.voltarMes(mesAno);

            // 2) Busca os totais para preencher os campos da tela
            Connection con = dataSource.getConnection();
            String sql = "SELECT SUM(vlmesanterior) AS totalAnterior, "
                    + "SUM(vlmesatual) AS totalAtual, "
                    + "SUM(vlmesatual) - SUM(vlmesanterior) AS saldo "
                    + "FROM planodecontas";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                double totalAnterior = rs.getDouble("totalAnterior");
                double totalAtual = rs.getDouble("totalAtual");
                double saldo = rs.getDouble("saldo");

                // Exibe sempre valores absolutos
                anterior.setText(String.format("%.2f", Math.abs(totalAnterior)));
                atual.setText(String.format("%.2f", Math.abs(totalAtual)));

                // Exibe se o saldo é Débito ou Crédito
                credoudeb.setText(saldo >= 0 ? "Crédito" : "Débito");
            }

            JOptionPane.showMessageDialog(null, "Virada do mês " + mesAno + " realizada com sucesso!");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao realizar virada de mês: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnAttMesActionPerformed

    private void btnAttAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttAnoActionPerformed
        String anoStr = data.getText().trim();

        if (anoStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o ano para a virada!");
            return;
        }

        int ano;
        try {
            ano = Integer.parseInt(anoStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ano inválido! Informe apenas números, ex: 2025");
            return;
        }

// Cria a conexão
        DataSource dataSource = new DataSource();
        DaoRotinas dao = new DaoRotinas(dataSource);

        try {
            // 1) Executa a virada de ano
            dao.voltarAno(ano);

            // 2) Busca os totais para preencher os campos da tela
            Connection con = dataSource.getConnection();
            String sql = "SELECT SUM(vlmesanterior) AS totalAnterior, "
                    + "       SUM(vlmesatual) AS totalAtual, "
                    + "       SUM(vlmesatual) - SUM(vlmesanterior) AS saldo "
                    + "FROM planodecontas";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                double totalAnterior = rs.getDouble("totalAnterior");
                double totalAtual = rs.getDouble("totalAtual");
                double saldo = rs.getDouble("saldo");

                // Exibe sempre valores absolutos
                anterior.setText(String.format("%.2f", Math.abs(totalAnterior)));
                atual.setText(String.format("%.2f", Math.abs(totalAtual)));

                // Exibe se o saldo é Débito ou Crédito
                credoudeb.setText(saldo >= 0 ? "Débito" : "Crédito");
            }

            JOptionPane.showMessageDialog(null, "Virada do ano " + ano + " realizada com sucesso!");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao realizar virada de ano: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnAttAnoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desatualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desatualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desatualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desatualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desatualizacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anterior;
    private javax.swing.JTextField atual;
    private javax.swing.JButton btnAttAno;
    private javax.swing.JButton btnAttMes;
    private javax.swing.JTextField credoudeb;
    private javax.swing.JTextField data;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
