package view;

import javax.swing.JOptionPane;

/**
 *
 * @author krug
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */

    public Menu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Movimentacao = new javax.swing.JCheckBoxMenuItem();
        PlanoDeContas = new javax.swing.JCheckBoxMenuItem();
        Usuarios = new javax.swing.JCheckBoxMenuItem();
        FichaRazao = new javax.swing.JCheckBoxMenuItem();
        Atualizacao = new javax.swing.JCheckBoxMenuItem();
        Desatualizacao = new javax.swing.JCheckBoxMenuItem();
        Balancete = new javax.swing.JCheckBoxMenuItem();
        Balanco = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Sair = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 911, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastros");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        Movimentacao.setSelected(true);
        Movimentacao.setText("Movimentacao");
        Movimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimentacaoActionPerformed(evt);
            }
        });
        jMenu1.add(Movimentacao);

        PlanoDeContas.setSelected(true);
        PlanoDeContas.setText("Plano de Contas");
        PlanoDeContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlanoDeContasActionPerformed(evt);
            }
        });
        jMenu1.add(PlanoDeContas);

        Usuarios.setSelected(true);
        Usuarios.setText("Usuarios");
        Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(Usuarios);

        FichaRazao.setSelected(true);
        FichaRazao.setText("Ficha Razao");
        FichaRazao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FichaRazaoActionPerformed(evt);
            }
        });
        jMenu1.add(FichaRazao);

        Atualizacao.setSelected(true);
        Atualizacao.setText("Atualizacao");
        Atualizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizacaoActionPerformed(evt);
            }
        });
        jMenu1.add(Atualizacao);

        Desatualizacao.setSelected(true);
        Desatualizacao.setText("Desatualizacao");
        Desatualizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesatualizacaoActionPerformed(evt);
            }
        });
        jMenu1.add(Desatualizacao);

        Balancete.setSelected(true);
        Balancete.setText("Balancete");
        Balancete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceteActionPerformed(evt);
            }
        });
        jMenu1.add(Balancete);

        Balanco.setSelected(true);
        Balanco.setText("Balanco");
        Balanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalancoActionPerformed(evt);
            }
        });
        jMenu1.add(Balanco);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sair");

        Sair.setSelected(true);
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        jMenu2.add(Sair);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimentacaoActionPerformed
        Movimentacao janela = new Movimentacao();
        jDesktopPane.add(janela);
        janela.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_MovimentacaoActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
    int opcao = JOptionPane.showConfirmDialog(null, "Deseja sair do aplicativo?", "Atenção", JOptionPane.YES_OPTION);
        
        if (opcao == JOptionPane.YES_OPTION){
            System.exit(0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_SairActionPerformed

    private void PlanoDeContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlanoDeContasActionPerformed
        PlanoDeContas janela = new PlanoDeContas();
        jDesktopPane.add(janela);
        janela.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_PlanoDeContasActionPerformed

    private void UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosActionPerformed
        Usuarios janela = new Usuarios();
        jDesktopPane.add(janela);
        janela.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_UsuariosActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void FichaRazaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FichaRazaoActionPerformed
        FichaRazao janela = new FichaRazao();
        janela.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_FichaRazaoActionPerformed

    private void AtualizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizacaoActionPerformed
        Atualizacao janela = new Atualizacao();
        janela.setVisible(true);             // TODO add your handling code here:
    }//GEN-LAST:event_AtualizacaoActionPerformed

    private void DesatualizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesatualizacaoActionPerformed
        Desatualizacao janela = new Desatualizacao();
        janela.setVisible(true);             // TODO add your handling code here:
    }//GEN-LAST:event_DesatualizacaoActionPerformed

    private void BalanceteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceteActionPerformed
        Balancete janela = new Balancete();
        janela.setVisible(true);             // TODO add your handling code here:
    }//GEN-LAST:event_BalanceteActionPerformed

    private void BalancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalancoActionPerformed
        Balanco janela = new Balanco();
        janela.setVisible(true);
    }//GEN-LAST:event_BalancoActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem Atualizacao;
    private javax.swing.JCheckBoxMenuItem Balancete;
    private javax.swing.JCheckBoxMenuItem Balanco;
    private javax.swing.JCheckBoxMenuItem Desatualizacao;
    private javax.swing.JCheckBoxMenuItem FichaRazao;
    private javax.swing.JCheckBoxMenuItem Movimentacao;
    private javax.swing.JCheckBoxMenuItem PlanoDeContas;
    private javax.swing.JCheckBoxMenuItem Sair;
    private javax.swing.JCheckBoxMenuItem Usuarios;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
