/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import dao.DaoPlanoDeContas;
import dao.DataSource;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guilherme.krug
 */
public class PlanoDeContas extends javax.swing.JInternalFrame {

    /**
     * Creates new form PlanoDeContas1
     */
    public PlanoDeContas() {
        initComponents();
        
        readJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnFechar4 = new javax.swing.JButton();
        btnAdd4 = new javax.swing.JButton();
        btnExcluir4 = new javax.swing.JButton();
        btnAlterar4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("PLANO DE CONTAS");

        jtfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPesquisarActionPerformed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnFechar4.setBackground(new java.awt.Color(242, 242, 242));
        btnFechar4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFechar4.setText("FECHAR");
        btnFechar4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnFechar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechar4ActionPerformed(evt);
            }
        });

        btnAdd4.setBackground(new java.awt.Color(242, 242, 242));
        btnAdd4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd4.setText("ADICIONAR");
        btnAdd4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAdd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd4ActionPerformed(evt);
            }
        });

        btnExcluir4.setBackground(new java.awt.Color(242, 242, 242));
        btnExcluir4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir4.setText("EXCLUIR");
        btnExcluir4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnExcluir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluir4ActionPerformed(evt);
            }
        });

        btnAlterar4.setBackground(new java.awt.Color(242, 242, 242));
        btnAlterar4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAlterar4.setText("ALTERAR");
        btnAlterar4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAlterar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAlterar4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdd4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFechar4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFechar4, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(btnAdd4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Conta", "ID Reduzida", "Descrição", "VL EX Anterior", "DS EX Anterior", "VL EX Atual", "DS EX Atual", "VL Mês Anterior", "DS Mês Anterior", "VL Mês Atual", "DS Mês Atual"
            }
        ));
        jScrollPane2.setViewportView(jTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPesquisarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        String campo = jtfPesquisar.getText();
        if (campo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o nome do usuário");
        }
        else {
            preencheJTable(campo);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnFechar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechar4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFechar4ActionPerformed

    private void btnAdd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd4ActionPerformed
        PlanoDeContasIncluir jan = new PlanoDeContasIncluir();
        jan.setVisible(true);
    }//GEN-LAST:event_btnAdd4ActionPerformed

    private void btnExcluir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluir4ActionPerformed
        PlanoDeContasExcluir jan = new PlanoDeContasExcluir();
        jan.setVisible(true);
    }//GEN-LAST:event_btnExcluir4ActionPerformed

    private void btnAlterar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterar4ActionPerformed
        PlanoDeContasAlterar jan = new PlanoDeContasAlterar();
        jan.setVisible(true);
    }//GEN-LAST:event_btnAlterar4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    readJTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void readJTable() {
    DefaultTableModel modelo = (DefaultTableModel) jTable.getModel();

    // Ajuste de largura das colunas conforme necessidade
    jTable.getColumnModel().getColumn(0).setPreferredWidth(20);  // idConta
    jTable.getColumnModel().getColumn(1).setPreferredWidth(30);  // idReduzida
    jTable.getColumnModel().getColumn(2).setPreferredWidth(100); // dsDescricao
    jTable.getColumnModel().getColumn(3).setPreferredWidth(40);  // vlExAnterior
    jTable.getColumnModel().getColumn(4).setPreferredWidth(30);  // dsExAnteriorDC
    jTable.getColumnModel().getColumn(5).setPreferredWidth(40);  // vlExAtual
    jTable.getColumnModel().getColumn(6).setPreferredWidth(30);  // dsExAtualDC
    jTable.getColumnModel().getColumn(7).setPreferredWidth(40);  // vlMesAnterior
    jTable.getColumnModel().getColumn(8).setPreferredWidth(30);  // dsMesAnteriorDC
    jTable.getColumnModel().getColumn(9).setPreferredWidth(40);  // vlMesAtual
    jTable.getColumnModel().getColumn(10).setPreferredWidth(30); // dsMesAtualDC

    modelo.setNumRows(0);

    DataSource dataSource = new DataSource();
    DaoPlanoDeContas daoConta = new DaoPlanoDeContas(dataSource);

    for (model.PlanoDeContas c : daoConta.readAll()) {
        modelo.addRow(new Object[]{
            c.getIdConta(),
            c.getIdReduzida(),
            c.getDsDescricao(),
            c.getVlExAnterior(),
            c.getDsExAnteriorDC(),
            c.getVlExAtual(),
            c.getDsExAtualDC(),
            c.getVlMesAnterior(),
            c.getDsMesAnteriorDC(),
            c.getVlMesAtual(),
            c.getDsMesAtualDC()
        });
    }

    dataSource.closeDataSource();
}

private void preencheJTable(String campo) {
    DefaultTableModel modelo = (DefaultTableModel) jTable.getModel();

    jTable.getColumnModel().getColumn(0).setPreferredWidth(20);  // idConta
    jTable.getColumnModel().getColumn(1).setPreferredWidth(30);  // idReduzida
    jTable.getColumnModel().getColumn(2).setPreferredWidth(100); // dsDescricao
    jTable.getColumnModel().getColumn(3).setPreferredWidth(40);  // vlExAnterior
    jTable.getColumnModel().getColumn(4).setPreferredWidth(30);  // dsExAnteriorDC
    jTable.getColumnModel().getColumn(5).setPreferredWidth(40);  // vlExAtual
    jTable.getColumnModel().getColumn(6).setPreferredWidth(30);  // dsExAtualDC
    jTable.getColumnModel().getColumn(7).setPreferredWidth(40);  // vlMesAnterior
    jTable.getColumnModel().getColumn(8).setPreferredWidth(30);  // dsMesAnteriorDC
    jTable.getColumnModel().getColumn(9).setPreferredWidth(40);  // vlMesAtual
    jTable.getColumnModel().getColumn(10).setPreferredWidth(30); // dsMesAtualDC

    modelo.setNumRows(0);

    DataSource dataSource = new DataSource();
    DaoPlanoDeContas daoConta = new DaoPlanoDeContas(dataSource);

    for (model.PlanoDeContas c : daoConta.consulta(campo)) {
        modelo.addRow(new Object[]{
            c.getIdConta(),
            c.getIdReduzida(),
            c.getDsDescricao(),
            c.getVlExAnterior(),
            c.getDsExAnteriorDC(),
            c.getVlExAtual(),
            c.getDsExAtualDC(),
            c.getVlMesAnterior(),
            c.getDsMesAnteriorDC(),
            c.getVlMesAtual(),
            c.getDsMesAtualDC()
        });
    }

    dataSource.closeDataSource();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd4;
    private javax.swing.JButton btnAlterar4;
    private javax.swing.JButton btnExcluir4;
    private javax.swing.JButton btnFechar4;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jtfPesquisar;
    // End of variables declaration//GEN-END:variables
}
