package view;

import model.PlanoDeContas;
import model.Movimentacao;
import dao.DaoPlanoDeContas;
import dao.DaoMovimentacao;
import dao.DataSource;
import javax.swing.*;           // Para JFrame, JButton, JLabel, JTextField, JOptionPane, JTextArea
import java.awt.event.*;        // Para ActionEvent e ActionListener
import java.time.LocalDate;     // Para trabalhar com datas
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException; // Para tratar erros de parsing de data
import java.util.*;             // Para List, Map, HashMap
import java.util.stream.*;           // Para List, Map, HashMap

/**
 *
 * @author guilherme.krug
 */
public class Totalizacao extends javax.swing.JFrame {

    /**
     * Creates new form Totalizacao
     */
    public Totalizacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalGeralLabel = new javax.swing.JTextField();
        quantidadeLabel = new javax.swing.JTextField();
        btnUptade = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dataFinalField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subtotalTextArea = new javax.swing.JTextArea();
        dataInicialField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        totalGeralLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalGeralLabelActionPerformed(evt);
            }
        });

        btnUptade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUptade.setText("INSERIR MOVIMENTAÇÃO PARA ATUALIZAR PLANO");
        btnUptade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUptadeActionPerformed(evt);
            }
        });

        jLabel4.setText("Subtotal por Plano de Contas");

        jLabel3.setText("Quantidade de movimentações");

        jLabel5.setText("Total Geral");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Data de início (xx/xx/xxxx)");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Data de fim (xx/xx/xxxx)");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("TOTALIZAÇÃO");

        subtotalTextArea.setColumns(20);
        subtotalTextArea.setRows(5);
        jScrollPane1.setViewportView(subtotalTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(15, 15, 15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataFinalField, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataInicialField, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(quantidadeLabel)
                            .addComponent(totalGeralLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(btnUptade)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dataInicialField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(dataFinalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(totalGeralLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(quantidadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUptade)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalGeralLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalGeralLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalGeralLabelActionPerformed

    private void btnUptadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUptadeActionPerformed
        // Formatter para datas no formato dd/MM/yyyy
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        // Variáveis de filtro
        LocalDate dataInicial = null;
        LocalDate dataFinal = null;

        // Ler datas do usuário
        try {
            if (!dataInicialField.getText().isEmpty()) {
                dataInicial = LocalDate.parse(dataInicialField.getText(), formatter);
            }
            if (!dataFinalField.getText().isEmpty()) {
                dataFinal = LocalDate.parse(dataFinalField.getText(), formatter);
            }
        } catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(null, "Formato de data inválido! Use dd/MM/yyyy");
            return;
        }

        // Inicializar DataSource e DAOs
        DataSource dataSource = new DataSource(); // certifique-se que seu construtor inicializa a conexão
        DaoMovimentacao daoMovimentacao = new DaoMovimentacao(dataSource);
        DaoPlanoDeContas daoContas = new DaoPlanoDeContas(dataSource);

        // Pegar todas as movimentações do DAO
        ArrayList<Movimentacao> movimentacoes = daoMovimentacao.readAll();

        // Filtrar por data
        ArrayList<Movimentacao> movimentacoesFiltradas = new ArrayList<>();
        for (Movimentacao m : movimentacoes) {
            LocalDate dataMov = LocalDate.parse(m.getDtMovimento(), formatter);
            boolean depoisInicial = (dataInicial == null) || !dataMov.isBefore(dataInicial);
            boolean antesFinal = (dataFinal == null) || !dataMov.isAfter(dataFinal);
            if (depoisInicial && antesFinal) {
                movimentacoesFiltradas.add(m);
            }
        }

        // Calcular total geral
        double totalGeral = 0;
        for (Movimentacao m : movimentacoesFiltradas) {
            totalGeral += m.getVlMovimento();
        }

        // Calcular total por plano de contas (idreduzida)
        Map<Integer, Double> totalPorPlano = new HashMap<>();
        for (Movimentacao m : movimentacoesFiltradas) {
            int idPlano = m.getIdReduzida();
            totalPorPlano.put(idPlano, totalPorPlano.getOrDefault(idPlano, 0.0) + m.getVlMovimento());
        }

        // Quantidade de registros
        int quantidade = movimentacoesFiltradas.size();

        // Atualizar tela
        totalGeralLabel.setText(String.format("%.2f", totalGeral));
        quantidadeLabel.setText(String.valueOf(quantidade));
        subtotalTextArea.setText("");

        // Preencher subtotal por plano de contas
        for (Map.Entry<Integer, Double> entry : totalPorPlano.entrySet()) {
            // Buscar conta pelo idreduzida usando o método de instância
            ArrayList<PlanoDeContas> contasList = daoContas.consulta(String.valueOf(entry.getKey()));
            String descricaoPlano = "Desconhecido";
            if (!contasList.isEmpty()) {
                descricaoPlano = contasList.get(0).getDsDescricao();
            }

            // Atualizar JTextArea
            subtotalTextArea.setText(
                subtotalTextArea.getText() + descricaoPlano + ": " + String.format("%.2f", entry.getValue()) + "\n"
            );
        }
    }//GEN-LAST:event_btnUptadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Totalizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Totalizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Totalizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Totalizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Totalizacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnUptade;
    private javax.swing.JTextField dataFinalField;
    private javax.swing.JTextField dataInicialField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField quantidadeLabel;
    private javax.swing.JTextArea subtotalTextArea;
    private javax.swing.JTextField totalGeralLabel;
    // End of variables declaration//GEN-END:variables
}
